echo "node_modules/" >> .gitignore
echo "*/node_modules/" >> .gitignore
echo "dist/" >> .gitignore
echo "*/dist/" >> .gitignore
echo "build/" >> .gitignore
echo "*/build/" >> .gitignore
echo ".env.local" >> .gitignore
echo ".DS_Store" >> .gitignore
echo "*.zip" >> .gitignore